plugins {
    id 'com.android.application'
}

android {
    namespace 'com.vf6.splitmirror'
    compileSdk 34

    defaultConfig {
        applicationId 'com.vf6.splitmirror'
        minSdk 29
        targetSdk 33
        versionCode 1
        versionName '0.1.0'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.annotation:annotation:1.7.1'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'com.github.martoreto:aauto-sdk:v4.6'
}
